name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: [ "bug", "triage" ]
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      placeholder: |-
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: For example, Windows, Ubuntu, or RHEL.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System Version
      description: For example, 19042.2486, 22.01, 7.5.
    validations:
      required: true
  - type: input
    attributes:
      label: MSBuild Version
      description: For example, 17.4.0.51802. Obtainable using `dotnet msbuild --version`.
    validations:
      required: true
  - type: input
    attributes:
      label: .NET SDK Version
      description: For example, 7.0.100. Obtainable using `dotnet --version`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
