name: Feature request
description: Suggest an idea for this project
title: '[Feature]: '
labels: [ "enhancement", "triage" ]
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
