name: Other
description: Submit an uncategorized issue
title: '[Other]: '
labels: [ "other" ]
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
